import {
  SCALEBUN_APP_ID,
  SCALEBUN_CLIENT_KEY,
  SCALEBUN_PROJECT_ID,
  SCALEBUN_PUBLISHABLE_KEY,
  SCALEBUN_ENVIRONMENT,
  SCALEBUN_PROJECT_NAME,
  SCALEBUN_OTA_CHANNEL,
  SCALEBUN_OTA_ENABLED,
  SCALEBUN_DESKTOP_DEBUG_HOST,
  NETWORK_TEST_SERVER_URL,
  ENABLE_DANGEROUS_TESTS,
} from '@env';
import { validateEnv, type RawEnv, type LabEnv } from './envValidation';

export type { LabEnv, CredentialState } from './envValidation';

const raw: RawEnv = {
  SCALEBUN_APP_ID,
  SCALEBUN_CLIENT_KEY,
  SCALEBUN_PROJECT_ID,
  SCALEBUN_PUBLISHABLE_KEY,
  SCALEBUN_ENVIRONMENT,
  SCALEBUN_PROJECT_NAME,
  SCALEBUN_OTA_CHANNEL,
  SCALEBUN_OTA_ENABLED,
  SCALEBUN_DESKTOP_DEBUG_HOST,
  NETWORK_TEST_SERVER_URL,
  ENABLE_DANGEROUS_TESTS,
};

export const ENV: LabEnv = validateEnv(raw, { isDev: __DEV__ });
